.TH iprv 1 22-MAY-2022 "Kozmix Go"

.SH NAME
iprv \- calculate electrical current, power, resistance and/or voltage

.SH SYNOPSIS
.B iprv
[I=val] [V=val] [P=val] [R=val]

.SH DESCRIPTION
.BR iprv,
given any two out of electrical current, power, resistance or
voltage, will calculate the other two values. You must call
.B iprv
with exactly two arguments.

.SH OPTIONS
.TP
.B I=val
specify current in Amperes (alias: i)
.TP
.B V=val
specify voltage in Volts (alias: v)
.TP
.B P=val
specify power in Watts (alias: p)
.TP
.B R=val
specify resistance in Ohms (alias: r)

.B iprv
accepts SI prefixes (k, M, μ etc.) as part of its command line
options.

.SH EXAMPLE
.EX
$ iprv r=8 v=5.23
vr to ip
resistance: R = 8
voltage:    V = 5.23
current:    I = 0.654
power:      P = 3.42
.EE

.SH AUTHOR
svm

