.TH ipvr 1 19-May-2022 "Kozmix GO"

.SH NAME
ipvr \- calculate electrical current, power, resistance and/or voltage

.SH SYNOPSIS
.B ipvr
[I=val] [V=val] [P=val] [R=val]

.SH DESCRIPTION
.BR ipvr,
given almost any two out of electrical current, power, resistance or
voltage, will calculate the missing two values. You must call
.B ipvr
with exactly two arguments.

.SH OPTIONS
.TP
.B I=val
specify current in Amperes (aliases: i, A, a)
.TP
.B V=val
specify voltage in Volts (alias: v)
.TP
.B P=val
specify power in Watts (alias: p)
.TP
.B R=val
specify resistance in Ohms (alias: r)

.SH EXAMPLE
.EX
$ iprv r=8 v=5.23
vr to ip
current:    I = 0.654
power:      P = 3.42
voltage:    V = 5.23
resistance: R = 8
.EE

.SH BUGS
.B ipvr P=val R=val
doesn't work. This is due to a bug in the universe, not in this programme.

.SH AUTHOR
svm

