.TH iprv 1 14-JAN-2023 "Kozmix Go"

.SH NAME
iprv \- calculate electrical current, power, resistance and/or voltage

.SH SYNOPSIS
.B iprv
[I=val] [V=val] [P=val] [R=val]

.SH DESCRIPTION
.BR iprv,
given any two out of electrical current, power, resistance or
voltage, will calculate the other two values. You must call
.B iprv
with exactly two arguments.

.SH OPTIONS

.B iprv
accepts SI prefixes (k, M, μ etc.) as part of its command line
options, which are:

.TP
.B I=val
specify current in amperes (alias: i)
.TP
.B V=val
specify voltage in volts (alias: v)
.TP
.B P=val
specify power in watts (alias: p)
.TP
.B R=val
specify resistance in ohms (alias: r)

.SH EXAMPLE
.EX
$ iprv r=8 v=5.23
resistance R = 8Ω
voltage    V = 5.23V
current    I = 654mA
power      P = 3.419W
.EE

.SH AUTHOR
svm

